impl search service and returning string functions
Angel-dev14/DIANS pull request #27
Opened 2021-12-10 17:55 UTC by jovanasmilevska

Searchot e so post baranje vo thymeleaf ne moze inputot da se zeme i da se prati kako path variable

2021-12-10 19:08 UTC, Angel-dev14 requested changes
Fali PlacesFinder toa mesto posebnite repostitory isto kako kaj diagramot kaj koceptualnata arhitektura

2021-12-10 19:08 UTC, Angel-dev14 commented on domasna3/navigation/src/main/java/com/dians/navigation/controller/MainController.java
>  public class MainController {
rename vo SearchController

2021-12-10 19:08 UTC, Angel-dev14 commented on domasna3/navigation/src/main/java/com/dians/navigation/controller/MainController.java
> +    public String searchBar(@RequestParam(required = false) String filter, Model model){
Ova Get treba da bide

2021-12-10 19:08 UTC, Angel-dev14 commented on domasna3/navigation/src/main/java/com/dians/navigation/controller/MainController.java
> +
trgni gi komentarive

2021-12-10 19:08 UTC, Angel-dev14 commented on domasna3/navigation/src/main/java/com/dians/navigation/repository/FastFoodRepository.java
> +    List<String> findAllFastFoods();
findAllFastFoodNames

2021-12-10 19:08 UTC, Angel-dev14 commented on domasna3/navigation/src/main/java/com/dians/navigation/repository/FastFoodRepository.java
> +    List<String> findAllFastFoodsByName(String place);
findAllFastFoodNamesFromPlaceName

2021-12-10 19:08 UTC, Angel-dev14 commented on domasna3/navigation/src/main/java/com/dians/navigation/repository/PubRepository.java
> +    List<String> findAllPubs();
isto kako kaj fastFoods

2021-12-10 19:09 UTC, Angel-dev14 commented
> Searchot e so post baranje vo thymeleaf ne moze inputot da se zeme i da se prati kako path variable
Ne ti treba path variable tuka samo query string treba da se prati so RequestParam

2021-12-10 20:45 UTC, jovanasmilevska commented
okej se ama placesfinder ne moze da se napravi dvata repozitoriumi se interfejsi za da gi stavam vo placesfinder mora da gi implementira site metodi toa e dopolnitelen kod nepotreben, probav i so apstraktni klasi nikako ne mozese
mora da ima poseben repozitorium za prostapuvanje do sekoja tabela

2021-12-11 11:00 UTC, agonosmani requested changes
Ne si go komitnala SearchService

2021-12-11 17:06 UTC, merged